global:
  scrape_interval: 15s

scrape_configs:
  #=> Scrape directo al Quarkus auth-service (métricas nativas)
  - job_name: "quarkus-auth-service"
    metrics_path: /q/metrics
    static_configs:
      - targets: ["auth-service:8083"]

  #=> Scrape de métricas procesadas/exportadas por el OpenTelemetry Collector
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]
