mp:
  messaging:
    outgoing:
      auth-events-out:
        connector: smallrye-kafka
        topic: auth-events
        value.serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
        bootstrap.servers: ${QUARKUS_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

    incoming:
      auth-events-in:
        connector: smallrye-kafka
        topic: auth-events
        value.deserializer: io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
        auto.offset.reset: earliest
        bootstrap.servers: ${QUARKUS_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

quarkus:
  oidc:
    auth-server-url: ${OIDC_URL:${vault:myapp.auth-server-url}}
    client-id: "auth-service-client"
    credentials:
      secret: ${OIDC_SECRET:${vault:myapp.client-secret}}
    tls:
      verification: none
    application-type: service
    authentication:
      user-info-required: false
    token:
      principal-claim: preferred_username
      role-claim-path: realm_access.roles
      verify-access-token-audience: true

  mongodb:
    connection-string: ${QUARKUS_MONGODB_CONNECTION_STRING:mongodb://mongo:27017}
    database: "auth-db"

  redis:
    hosts: "redis://${REDIS_HOST:redis}:${REDIS_PORT:6379}"
    timeout: "100s"
    client-name: "auth-redis-client"
    client-type: standalone

  kafka:
    bootstrap-servers: ${QUARKUS_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

  opentelemetry:
    enabled: true
    tracer:
      exporter:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4317}
          protocol: grpc
      resource-attributes: service.name=auth-service

  micrometer:
    enabled: true
    registry-enabled-default: true
    registry:
      prometheus:
        enabled: true

  management:
    enabled: true
    root-path: /q        # ✅ asegura que las rutas estén bajo /q
    endpoints:
      all:
        enabled: true
      prometheus:
        enabled: true    # ✅ habilita prometheus explícitamente
        path: /metrics   # ✅ la ruta queda en /q/metrics
    network-interface: 0.0.0.0 # <-- Esto soluciona el acceso en Docker

  smallrye-metrics:
    enabled: true        # ✅ habilita smallrye métricas
    extensions:
      enabled: true

  vault:
    url: ${QUARKUS_VAULT_URL:http://vault:8200}
    authentication:
      client-token: root
    kv-secret-engine-mount-path: secret
    kv-secret-engine-version: 2

  http:
    port: 8083

  log:
    level: "INFO"
    console:
      enable: true
      color: true
      level: "DEBUG"
    file:
      enable: true
      path: "/app/logs/auth-service.log"
    category:
      "com.webinarnttdata": { level: DEBUG }
      "io.quarkus.oidc": { level: DEBUG }
      "io.quarkus.security": { level: DEBUG }
      "org.apache.kafka": { level: DEBUG }
      "io.smallrye.reactive.messaging.kafka": { level: DEBUG }

resilience4j.circuitbreaker:
  instances:
    userClient:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s

resilience4j.retry:
  instances:
    userClient:
      maxAttempts: 3
      waitDuration: 2s
