FROM quay.io/quarkus/quarkus-micro-image:2.0
WORKDIR /work/

# Copiar el binario nativo generado por Quarkus
COPY target/auth-service-1.0.0-SNAPSHOT-runner /work/application

# Dar permisos de ejecución
RUN chmod 775 /work/application

EXPOSE 8083

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
