name: CI - Quarkus Auth Service Native

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Compilar en modo nativo con Quarkus
      - name: Build Native Image with Maven
        run: mvn clean package -Pnative -DskipTests=false

      # 4. Verificar archivos generados
      - name: List target directory
        run: ls -l target

      # 5. Login en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Verificación del login
      - name: Verify Docker Login
        run: docker info

      # 7. Construir imagen Docker (Native)
      - name: Build Docker Image (Native)
        run: |
          docker build \
            -f src/main/docker/Dockerfile.native \
            -t ${{ secrets.DOCKER_USERNAME }}/auth-service-native:1.0.1 .

      # 8. Subir imagen a Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/auth-service-native:1.0.1
